Add `terminate_session()`
zeek/spicy-plugin pull request #107
Opened 2022-04-12 09:00 UTC by rsmmr

This supersedes #105 and is on top of #103.

2022-04-13 08:44 UTC, bbannier requested changes

2022-04-14 09:29 UTC, rsmmr commented on src/runtime-support.cc
> +        throw spicy::zeek::rt::ValueUnavailable("terminate_session() not available in the curent context");
I don't think we should silently ignore it, I'll add a note to the docs.

2022-04-15 17:04 UTC, luxanna91 commented on tests/zeek/terminate-session.zeek
> +# @TEST-EXEC: ${ZEEK} -b -r ${TRACES}/long-dns-connection.pcap Zeek::Spicy test.hlto base/protocols/conn %INPUT
It cames from wireshark pcap samples [page](https://wiki.wireshark.org/SampleCaptures), [direct download link](https://wiki.wireshark.org/uploads/__moin_import__/attachments/SampleCaptures/dns.cap)

2022-04-19 15:36 UTC, bbannier approved these changes

2022-04-20 07:40 UTC, merged